# oxocarbon

[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.search.matches]
foreground = "CellBackground"
background = "#ee5396"

[colors.footer_bar]
background = "#262626"
foreground = "#ffffff"

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"


[colors.cursor]
text = "0x0d1117"
cursor = "0xe6edf3"

[cursor]
blink_interval = 200
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "always"
shape = "Beam"

[font]
size = 16

[font.bold]
family = "Iosevka"
style = "Bold Extended"

[font.bold_italic]
family = "Iosevka"
style = "Bold Extended Italic"

[font.italic]
family = "Iosevka"
style = "Extended Italic"

[font.normal]
family = "Iosevka"
style = "Extended"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"


[env]
TERM = "alacritty"
